### ISSUE TITLE
Visualizando dados!

### ISSUE THREAD

**Issue by ftonato** [nicholasess/post-nodejs-mysql#3]
Estava pensando, o que acha de fazer um menu básico e as telas básicas para o crud (para melhor visualização dos dados)?

**Comment by nicholasess** [comment]
Estou fazendo isso em outro post, com angular e NodeJs.
Só procurar no blog, são os dois primeiros posts

**Comment by ftonato** [comment]
Ah blz, não tinha visto mesmo :)

Poderia colocar o link deles na página da série do "post-nodejs-mysql" ou até no readme.md (Sugestão)!

**Comment by nicholasess** [comment]
Beleza, farei isso

**Comment by nicholasess** [comment]
Obrigado pela sugestão

**Comment by nicholasess** [comment]
@ftonato o post da serie já está atualizado com o código do angular, obrigado pela preocupação,
abraços
